### ISSUE TITLE
border-radius not respected anymore

### ISSUE THREAD

**Issue by xewl** [cossssmin/tailwindcss-border-gradients#24]
It seems that this is not respecting the existing radius classes, eg `.rounded-full` 
Is this even possible to adhere?

**Comment by cossssmin** [comment]
Not possible with borders - the [spec says no](https://www.w3.org/TR/css-backgrounds-3/#corner-clipping). You could try with [background gradients](https://stackoverflow.com/a/53037637) instead.

**Comment by xewl** [comment]
Found a workaround with a background gradient on a pseudo element 👍
